name: Log Contexts

on: push

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Lets log all context
        run: |
          echo ${{ github.action }}
          echo ${{ github.action_path }}
