name: Log Contexts

on: push

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          # ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: Git Stuff
        run: |
          git status
