name: Chromatic

on: push

jobs:
  publish-react-mark-docs:
    name: "Publish React Mark JS Docs"
    runs-on: ubuntu-latest
    # if: "contains(${{github.event.commits.*.message}}, 'publish react-mark-js docs')"
    steps:
      - name: CHECKOUT appsparkler.github.io
        uses: actions/checkout@v2
        with:
          name: appsparkler/appsparkler.github.io
          GITHUB_WORKSPACE: ${{github.workspaces}}/appsparkler.github.io

      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: INSTALL DEPENDENCIES
        run: |
          yarn

      - name: BUILD DOCS
        run: |
          yarn build-storybook -c .storybook/react-mark.js/docs --docs -o react-mark-js-docs

      - name: CHECK
        run: |
          ls react-mark-js-docs
