name: Chromatic

on: push

jobs:
  publish-react-mark-docs:
    name: "Publish React Mark JS Docs"
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.message, 'publish react-mark-js docs')
    steps:
      - name: Testing New Workflow
        run: |
          echo "${{toJSON(github.event)}}"
