name: Chromatic

on: push

jobs:
  publish-react-mark-docs:
    name: "Publish React Mark JS Docs"
    runs-on: ubuntu-latest
    steps:
      - name: Testing New Workflow
        run: |
          echo "${{toJSON(github.event)}}"
