name: Publish React Mark JS Docs

on: push

jobs:
  publish-react-mark-docs:
    name: "Publish React Mark JS Docs"
    runs-on: ubuntu-latest
    # if: "contains(${{github.event.commits.*.message}}, 'publish react-mark-js docs')"
    steps:
      - name: CHECKOUT appsparkler.github.io
        uses: actions/checkout@v2
        with:
          repository: appsparkler/appsparkler.github.io
          path: appsparkler.github.io
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: CHECKOUT my-storybooks
        uses: actions/checkout@v2
        with:
          path: my-storybooks
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: TEST COPYING
        run: |
          mv my-storybooks/.storybook appsparkler.github.io/storybook-config
          ls appsparkler.github.io/storybook-config
          git init
          git remote add origin git@github.com:appsparkler/appsparkler.github.io.git
          git remote show origin
          git pull origin master
          git status
        env:
          ssh-key: ${{secrets.GH_SSH_KEY}}

      # - name: INSTALL DEPENDENCIES
      #   run: |
      #     yarn --cwd my-storybooks

      # - name: BUILD React Mark JS Docs
      #   run: |
      #     yarn --cwd my-storybooks build-storybook -c .storybook/react-mark.js/docs --docs -o docs/react-mark-js

      # - name: COPY DOCS
      #   run: |
      #     mkdir appsparkler.github.io/docs
      #     mv my-storybooks/docs/react-mark-js appsparkler.github.io/docs/
      #     ls appsparkler.github.io/docs

      # - name: PUSH 2 appsparkler.github.io
      #   run: |
      #     cd appsparkler.github.io
      #     git status
      #     git diff-index --quiet HEAD || git commit -am "react-mark-js docs" || git push origin HEAD --quiet
