# name of our action
name: "Push"
# the event that will trigger the action
on: push

# what the action will do
jobs:
  install:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      # NODE JS SETUP
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # CHECKOUT
      - name: Checkout
        uses: actions/checkout@v1

      # PREPARE REPOSITORY
      # - name: Prepare repository
      # run: git fetch --unshallow --tags

      # CACHE NODE MODULES
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      # CREATE RELEASE
      - name: Create Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          yarn install
          yarn lerna run build --scope @react-mark.js/lib
          yarn lerna publish --conventional-commits -y

      # - uses: chromaui/action@v1
      #   # options required to the GitHub chromatic action
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_TOKEN }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
