name: CHROMATIC WORKFLOW

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    # SETUP PLATFORM
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT AND PULL CURRENT BRANCH
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # SETUP NodeJS
      - name: Setup NodeJS 15.11.0
        uses: actions/setup-node@v2
        with:
          node-version: "15.11.0"

      # CACHE NODE MODULES
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: |
            yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      # INSTALL PACKAGES
      - name: Install Packages
        run: |
          yarn install --prefer-offline --frozen-lockfile
          git status

      - name: Run Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GH_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          buildScriptName: build-sb-react-mark
