name: CHROMATIC SETUP

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    # SETUP PLATFORM
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT AND PULL CURRENT BRANCH
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # INSTALL PACKAGES
      - name: Install Packages
        run: |
          yarn install --prefer-offline --frozen-lockfile
          git status

      - name: Run Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GH_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          buildScriptName: build-sb-react-mark
