name: CHROMATIC WORKFLOW

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    # SETUP PLATFORM
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      # CHECKOUT AND PULL CURRENT BRANCH
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      # CONFIGURE GIT USER
      - name: Configure CI Git User
        run: |
          git config --global user.name '@appsparkler'
          git config --global user.email 'appsparkler@users.noreply.github.com'
          git remote set-url origin git@github.com:appsparkler/my-storybooks.git

      # SETUP NodeJS
      - name: Setup NodeJS 15.11.0
        uses: actions/setup-node@v2
        with:
          node-version: "15.11.0"

      # CACHE NODE MODULES
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: |
            ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      # INSTALL PACKAGES
      - name: Install Packages
        run: |
          yarn install --prefer-offline --frozen-lockfile

      # COMMIT AND PUSH ANY CHANGES
      - name: Commit & Push
        run: |
          git commit -am "chore: committing files after yarn install on CI [skip ci]"
          git push origin ${{ github.head_ref }}
        env:
          ssh-key: ${{ GH_SSH_KEY }}

      - name: Run Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GH_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          buildScriptName: build-sb-react-mark
