name: CHROMATIC SETUP

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    # SETUP PLATFORM
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT AND PULL CURRENT BRANCH
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # CACHE NODE MODULES
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: |
            **/node_modules
          key: |
            yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      # INSTALL PACKAGES
      - name: Install Packages
        run: |
          yarn install --prefer-offline --frozen-lockfile
          git status

      - name: Run Chromatic
        run: |
          yarn chromatic --project-token ${CHROMATIC_TOKEN} --build-script-name build-sb-react-mark
        env:
          CHROMATIC_TOKEN: ${{ secrets.CHROMATIC_TOKEN}}
