name: Testing Push Event

on: 
  push:
    paths:
      - '.github/**'
  
jobs:
  test-job:
    name: "Testing Conditional Execution"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'foos')"
    steps:

      - name: Echo
        run: |
          echo "Yes Foos"
